<a href="https://colab.research.google.com/github/Mohan0332/PyTorch_Tutorial/blob/master/Pytorch_Chapter0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Tensors

In [1]:
import torch

In [2]:
print(torch.__version__)

2.6.0+cu124


In [3]:
scalar = torch.tensor(4) #ndim = 0
scalar

tensor(4)

In [4]:
vector = torch.tensor([2,2])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#Matrix
matrix = torch.tensor([[1,2],[3,4]])

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
#TENSOR
Tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [11]:
Tensor.ndim

3

In [12]:
Tensor.shape

torch.Size([1, 3, 3])

In [13]:
Tensor[0].shape

torch.Size([3, 3])

 ### Creating a Random Tensor

In [14]:
rand_tensor = torch.rand(4,4,2)
rand_tensor

tensor([[[0.1155, 0.0464],
         [0.4679, 0.9717],
         [0.6920, 0.7222],
         [0.1760, 0.4599]],

        [[0.4839, 0.6326],
         [0.0621, 0.5132],
         [0.5741, 0.0337],
         [0.3190, 0.7369]],

        [[0.1139, 0.0053],
         [0.2685, 0.1982],
         [0.6896, 0.7254],
         [0.1075, 0.3089]],

        [[0.0038, 0.0481],
         [0.2745, 0.8645],
         [0.3568, 0.0526],
         [0.8171, 0.3571]]])

#### Zeros and Ones Tensor

In [15]:
# Tensor of zeros
zero_tensor = torch.zeros(2,3)
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
#Tensor of Ones
one_tensor = torch.ones(2,3)
one_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
one_tensor.dtype

torch.float32

Size and Shape:
- size is a function hence tensor.size() whereas shape is an attribute so its tensor.shape

### Matrix Multiplication

Two main ways of multiplication in neural nets and DL is:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [18]:
t1 = torch.tensor([[1,2],[3,4]])
t2 = torch.tensor([[5,10],[15,20]])
t1 * t2

tensor([[ 5, 20],
        [45, 80]])

In [19]:
torch.mm(t1,t2)


tensor([[ 35,  50],
        [ 75, 110]])

### Tensor Manipulation

In [20]:
a = torch.tensor([1,2,3,4,5,6])

In [21]:
#Min
a.min() , torch.min(a)
#Both the forms can be used

(tensor(1), tensor(1))

In [22]:
#Max
a.max() , torch.max(a)

(tensor(6), tensor(6))

In [23]:
#Mean
a.dtype

torch.int64

In [24]:
#Mean fucntion doesn't support dtypes other than float32, so convert it
a.type(torch.float32).mean(), torch.mean(a.type(torch.float32))

(tensor(3.5000), tensor(3.5000))

In [25]:
#Sum
a.sum() ,  torch.sum(a)

(tensor(21), tensor(21))

In [26]:
#Position of min and max we use argmin and argmax
b = torch.tensor([2,5,1,4,7,3])
b.argmax() , b.argmin()

(tensor(4), tensor(2))

#### Reshape

In [27]:
x = torch.arange(1.,10.)

In [28]:
x_reshaped = x.reshape(3,3)
x_reshaped[:,0] = 10
x_reshaped

tensor([[10.,  2.,  3.],
        [10.,  5.,  6.],
        [10.,  8.,  9.]])

#### View


In [29]:
x1 = torch.arange(2,11)
z = x1.view(1,9)
z , x1

(tensor([[ 2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [30]:
z[0,0] = 9
z , x1

(tensor([[ 9,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 9,  3,  4,  5,  6,  7,  8,  9, 10]))

***- Read about the memory sharing in view and reshape since both seem similar.***

#### Squeeze and Unsqueeze

In [31]:
x = torch.tensor([[1,2,3,4,]])

In [32]:
x_squeezed = x.squeeze() #Removes all the single size dimensions

In [33]:
x_squeezed.unsqueeze(dim=1) #added a dimension at the specified dim

tensor([[1],
        [2],
        [3],
        [4]])

#### Permute
- Shares the same memory

In [34]:
y = torch.zeros(2,4,3)

In [35]:
y.shape

torch.Size([2, 4, 3])

In [36]:
y_permute = y.permute(1,2,0)
y_permute.shape

torch.Size([4, 3, 2])

In [37]:
y[0,0,0] = 9
y

tensor([[[9., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [38]:
y_permute #Permute shares the same memory so y_permute also has "9" at(0,0,0)

tensor([[[9., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

####Indexing

In [39]:
a_sample = torch.tensor([[[1,2,3],
                          [4,5,6],
                          [7,8,9]]])
a_sample.shape

torch.Size([1, 3, 3])

In [40]:
a_sample[:,:,0] #Selects all values from 1st and 2nd dimension but only the 0th index values in the 3rd dimension

tensor([[1, 4, 7]])

#### Reproducability

In [43]:
random_seed = 24
torch.manual_seed(random_seed) #Makes sure that the randomness is reproducable.
tens = torch.rand(2,3)

#### Tensors on GPU

In [45]:
tensor = torch.tensor([4,5,6])

In [ ]:
tensor_in_gpu = tensor.to("cuda")